name: Release Packages

concurrency:
  group: release-${{ github.workflow }}-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: false

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  release:
    name: Publish to npm
    runs-on: ubuntu-latest
    if: >-
      ${{ github.event.workflow_run.conclusion == 'success' &&
          github.event.workflow_run.event == 'push' &&
          github.event.workflow_run.head_branch == 'main' }}
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
          always-auth: true

      - name: Install Dependencies
        run: npm ci

      # Build packages for the passed CI commit on main
      - name: Build Packages
        run: |
          npm -w packages/core run build
          npm -w packages/alert run build

      - name: Publish remark-itinerary
        run: |
          VERSION=$(node -e "const fs=require('fs');console.log(JSON.parse(fs.readFileSync('packages/core/package.json','utf8')).version)")
          if npm view remark-itinerary@"$VERSION" version > /dev/null 2>&1; then
            echo "remark-itinerary@$VERSION is already published. Skipping."
          else
            npm publish --workspace packages/core --provenance --access public
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish remark-itinerary-alert
        run: |
          VERSION=$(node -e "const fs=require('fs');console.log(JSON.parse(fs.readFileSync('packages/alert/package.json','utf8')).version)")
          if npm view remark-itinerary-alert@"$VERSION" version > /dev/null 2>&1; then
            echo "remark-itinerary-alert@$VERSION is already published. Skipping."
          else
            npm publish --workspace packages/alert --provenance --access public
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
